title: The Life of J Boogie
author: Jordan McGhee
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  ahaaahaaaa what it do babyyyyyy

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Jordan-McGhee # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
